# Generated by Django 4.2.4 on 2024-02-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('PhoneNo', models.CharField(max_length=50)),
                ('Complaint', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
