# Generated by Django 5.0.3 on 2024-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_complaint_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=15)),
                ('options', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=15)),
            ],
        ),
    ]
