# Generated by Django 5.0.3 on 2024-03-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_questions_student_dtls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='student_dtls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.student'),
        ),
    ]
