# Generated by Django 5.0.2 on 2024-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_phoneno_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
